apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      modulo: deployment1
  template:
    metadata:
      labels:
        modulo: deployment1
    spec: 
      containers:
      - name: pod3
        image: ulopeznovoa/k8s-red-help
        ports:
        - containerPort: 5000