apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      modulo: deployment2
  template:
    metadata:
      labels:
        modulo: deployment2
    spec: 
      containers:
      - name: pod2
        image: redis:alpine
        ports:
        - containerPort: 6379