apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  labels:
    modulo: servidor-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    modulo: servidor-web