apiVersion: v1
kind: Pod
metadata:
  name: mi-pod
  labels:
    modulo: servidor-web
spec:
  containers:
  - name: mi-contenedor
    image: ulopeznovoa/simple-web-80
    ports:
      - containerPort: 80