apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      modulo: servidor-web
  template:
      metadata:
        labels:
          modulo: servidor-web
      spec: 
        containers:
        - name: mi-pod
          image: httpd:alpine
          ports:
          - containerPort: 80