apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-vp
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  hostPath:
    path: ./Ejercicio3/volumen-persistente
  accessModes:
    - ReadWriteOnce